version: '3'

services:
  fetcher:
    build: ./fetcher
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: rb_solar
      SOLAR_ENDPOINT: http://10.43.60.63/
      FETCH_INTERVAL: 600
      PYTHONUNBUFFERED: 1

  webapp:
    image: docker.io/bitnami/laravel:9
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASE=rb_solar
    volumes:
      - './webapp:/app'

  database:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: rb_solar
    volumes:
      - './db_data:/var/lib/mysql'
      - './db_init.sql:/docker-entrypoint-initdb.d/db_init.sql'

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: database
      PMA_ARBITRARY: 1
